# 파이썬의 기본
## 생략하는 부분  
- print 소개 
- 계산 기능 소개  
- 문자열 합치기 + 로 나타내기 [개인블로그](https://passiondevelop.com/1-3-python-%eb%ac%b8%ec%9e%90%ec%97%b4/)
- 변수 할당 x = [3, 4, 5] 리스트 형태로 할당하기 [개인블로그](https://passiondevelop.com/1-3-2-python-%eb%b3%80%ec%88%98/)

## Numerical Python  
library numpy 사용

In [2]:
%pip install numpy matplotlib pandas

  Using cached numpy-2.2.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached matplotlib-3.10.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached contourpy-1.3.1-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.55.4-cp312-cp312-win_amd64.whl.metadata (169 kB)
  Using cached kiwisolver-1.4.8-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
  Using cached pillow-11.1.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
  Using cached pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached numpy-2.2.2-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached matplotlib-3.10.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached contourpy-1.3.1-cp

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np
# 배열 생성
x = np.array([3, 4, 5])
y = np.array([4, 7, 9])
# 2차원 배열 생성
X = np.array([[3,4,5], [4,7,9]])

In [8]:
print(x)
print(y)
print(X)

[3 4 5]
[4 7 9]
[[3 4 5]
 [4 7 9]]


[numpy array 공식문서](https://numpy.org/doc/2.1/reference/generated/numpy.array.html)  

"""
Parameters:  
    object : array_like  
        An array, any object exposing the array interface, an object whose __array__ method returns an array, or any sequence. If object is a scalar, a 0-dimensional array containing object is returned  
    dtype : data-type, optional  
        The desired(원하는) data-type for the array. If not given, NumPy will try to use a default dtype that can represent the values (by applying promotion rules when necessary)  
    copy : bool, optional  
        If True (default), then the array data is copied, If None, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.). Note that any copy of the data is shallow(얕은), i.e., for arrays with object dtype, the new array will point to the same objects. See Examples for ndarray.copy. For False it raises a ValueError if a copy cannot be avoided. Default: True.  
    order : {'K', 'A', 'C', 'F'}, optional  
        Specify(지정하다) the memory layout of the array. If object is not an array, the newly created array will be in C order(row major) unless 'F'is specified, in which case it will be in Fortran order(column major)  

        |--|--|--|
        |order|no copy|copy=True|
        |'K'|unchanged|F&C order preserved(보존된, 유지된), otherwise most similar order|
        |'A'|unchanged|F order if input is F and not C, otherwise C order|
        |'C'| C order | C order|
        |'F'| F order | F order|
    ndmin : int, optional
        Specifies the minimum number of dimensions that the resulting array dimensions that the resulting array should have. Ones will be prepended to the shape as needed to meet this requirement
    like : array_like, optional
        Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.
"""

In [9]:
# Upcating
a = np.array([1, 2, 3.0])
print(a)

[1. 2. 3.]


In [14]:
# Minimum dimensions 2
# ndmin = 대괄호 개수
b = np.array([1, 2, 3], ndmin=2)
print(b)

[[1 2 3]]


dtype : Overrides the data type of the result.
결과물의 데이터 타입을 지정한다.

In [20]:
# type provided
c = np.array([1, 2, 3], dtype=complex)
print(c)
c = np.array([1, 2, 3], dtype=int)
print(c)
c = np.array([1, 2, 3], dtype=float)
print(c)

[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]
[1. 2. 3.]


In [9]:
int_array = np.array([[1, 2], [3, 4]])
print("int_array type : " )
print(int_array.dtype)
print(type(int_array.dtype))
float_array = np.array([[1.0, 2.0], [3.0, 4.0]])
print("float_array type : ")
print(float_array.dtype)

int_array type : 
int64
<class 'numpy.dtypes.Int64DType'>
float_array type : 
float64


In [10]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [12]:
int_array = np.array([[1, 2], [3, 4]])
int_array

array([[1, 2],
       [3, 4]])

## .ndim
x의 속성에 접근하려면 x.attribute라고 입력한다.  
attribute 부분을 속성의 이름으로 바꾸어 쓰면 된다.  
x의 ndim 속성에 접근할 수 있다.  
x는 2차원 배열이다.  
x.dtype은 x 객체의 자료형(type)속성이다.  

In [16]:
print(int_array.ndim)
print(int_array.shape)

2
(2, 2)


sum() 메소드는 모든 원소를 합한다.

In [17]:
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

In [10]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape(2, 3)
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [5]:
x_reshape[0, 0]

np.int64(1)

In [7]:
print(x_reshape[1, 2])
print(x_reshape[1, 1])

6
5


In [11]:
print(x_reshape)
x_reshape[1, 1] = 100
print(x_reshape)

[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [  4 100   6]]


x_reshape이 수정되면  
x가 수정되는데 이는 x에서 같은 메모리를 참조하고 있기 때문  

In [13]:
print("x : ", x)
print("x_reshape : ", x_reshape)
x_reshape[1, 1] = 5
print("수정된 x_reshape : ", x_reshape)
print("수정된 x : ", x)

x :  [  1   2   3   4 100   6]
x_reshape :  [[  1   2   3]
 [  4 100   6]]
수정된 x_reshape :  [[1 2 3]
 [4 5 6]]
수정된 x :  [1 2 3 4 5 6]


## 랜덤데이터의 생성

In [5]:
import numpy as np
x = np.random.normal(size=50)
print(x)

[-1.26001168  1.12302422  0.92469941 -0.35090826 -1.26328414  0.61950225
 -1.78794724 -0.82520464  3.34850847 -1.41318454 -0.3291855   1.08487385
 -0.25509977  0.19569854  0.93643505 -0.4156125   0.02234177  0.56920562
 -0.84846286 -0.22950912 -1.29890861  1.1529203  -1.27504417  0.42655489
  0.5289949   0.9934646   1.00965319  0.33982219 -0.75640521  0.41551966
 -0.90605608 -0.40500337  1.49199327  0.0664024  -0.00757238  0.3419769
 -0.95715912 -2.54689017 -0.99248797  0.76385744  0.17275693 -1.61497449
  2.87824827  0.6116851   1.37386418  1.23459498  0.38510846  1.62502386
 -0.49451732 -0.21150386]


In [6]:
# x의 각 원소에 독립인 N(50, 1) 을 생성
y = x + np.random.normal(loc=50, scale=1, size=50)

In [7]:
# 상관관계
np.corrcoef(x, y)

array([[1.        , 0.75477306],
       [0.75477306, 1.        ]])

코드를 실행할 때마다 다른 결과값을 가져오는데  
random이 있어서 임 다만 고정적인 결과값을 표현하고 싶다면  
np.random.default_rng()함수를 사용하면 된다.  
임의의 사용자 지정 정수 인자를 넣어줌
np.random.default_rng(10) 데이터를 생성하기 전에
랜덤 시드를 설정하면 코드를 다시 실행해도 동일한 결과가 나온다.  

In [9]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


독자와의 동일한 결과를 보장해주기 위해  
default_rng()를 사용한다.  


np.mean(), np.var(), np.std() 함수를 사용해  
배열의 평균, 분산, 표준편차를 계산할 수 있음  

In [16]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [17]:
# 분산
np.var(y), y.var(), np.mean((y - y.mean())**2)

(np.float64(2.7243406406465125),
 np.float64(2.7243406406465125),
 np.float64(2.7243406406465125))

In [20]:
np.sqrt(np.var(y)), np.std(y)

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))

In [21]:
np.var?

Signature:      
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.var(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function var at 0x00000288F9AC32E0>
File:            c:\users\leep0\.conda\envs\bookpython\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of the flattened array.
  